services:
  sampo-dashboard: 
    container_name: rocrate-sampo-dashboard
    build:
      context: .
      dockerfile: .docker/sampo-ui/dev.dockerfile
    restart: unless-stopped
    tty: true
    networks:
      - web-network
    ports:
      - "8080:8080"
      - "3001:3001"
    volumes:
      - node_modules:/usr/src/app/node_modules/
      - ./src/client/translations/rocrate:/usr/src/app/src/client/translations/rocrate/
      - ./src/client/components/perspectives/rocrate:/usr/src/app/src/client/components/perspectives/rocrate/
      - ./src/client/components/main_layout/TopBar.js:/usr/src/app/src/client/components/main_layout/TopBar.js
      - ./src/client/img/rocrate:/usr/src/app/src/client/img/rocrate/
      - ./src/client/favicon.ico:/usr/src/app/src/client/favicon.ico
      - ./src/configs:/usr/src/app/src/configs/
      - ./src/server/sparql/rocrate:/usr/src/app/src/server/sparql/rocrate/
      - ./src/client/reducers/general/helpers.js:/usr/src/app/src/client/reducers/general/helpers.js
      - ./src/client/components/App.js:/usr/src/app/src/client/components/App.js

  jena-fuseki:
    container_name: rocrate-jena-fuseki
    image: stain/jena-fuseki
    platform: ${DOCKER_DEFAULT_PLATFORM:-linux/x86_64}
    restart: unless-stopped
    tty: true
    networks:
      - web-network
    ports:
      - "3030:3030"
    volumes:
      - jena-fuseki-data:/fuseki
      - ./.docker/fuseki/config.ttl:/fuseki/config.ttl
    environment:
      ADMIN_PASSWORD: ${FUSEKI_PASSWORD}

networks:
  web-network:
    name: rocrate-web-network

volumes:
  jena-fuseki-data:
    name: rocrate-data
  node_modules:
    name: rocrate-node_modules
