name: Upload to Jena Fuseki

on:
  push:
    branches:
      - main
    paths:
      - 'scripts/profile_urls.txt'
  workflow_dispatch:
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install dependencies
        run: python3 -m pip install -r requirements.workflow.txt
      - name: Run script
        run: |
          cd scripts
          python upload_profiles.py
        env:
          FUSEKI_UPLOAD_ENDPOINT: ${{ vars.ENV_FUSEKI_UPLOAD_ENDPOINT }}
          FUSEKI_PASSWORD: ${{ secrets.ENV_FUSEKI_PASSWORD }}

